package ohml.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCircuit = createDescriptorForCircuit();
  /*package*/ final ConceptDescriptor myConceptComponentGraph = createDescriptorForComponentGraph();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCircuit, myConceptComponentGraph);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Circuit:
        return myConceptCircuit;
      case LanguageConceptSwitch.ComponentGraph:
        return myConceptComponentGraph;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCircuit() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ohml", "Circuit", 0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c3fc5aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:66cd426c-b834-475f-8a3d-d7e3518c2104(ohml.structure)/1049114778041318490");
    b.version(2);
    b.aggregate("body", 0xe8f345509c41b68L).target(0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c41b6dL).optional(false).ordered(true).multiple(false).origin("1049114778041326440").done();
    b.alias("circuit");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComponentGraph() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ohml", "ComponentGraph", 0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c41b6dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:66cd426c-b834-475f-8a3d-d7e3518c2104(ohml.structure)/1049114778041326445");
    b.version(2);
    return b.create();
  }
}
