package deklund.util.units.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum CoreUnitEnum {
  ohm("ohm", null),
  volt("volt", "volt");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private CoreUnitEnum(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<CoreUnitEnum> getConstants() {
    List<CoreUnitEnum> list = ListSequence.fromList(new LinkedList<CoreUnitEnum>());
    ListSequence.fromList(list).addElement(CoreUnitEnum.ohm);
    ListSequence.fromList(list).addElement(CoreUnitEnum.volt);
    return list;
  }
  public static CoreUnitEnum getDefault() {
    return CoreUnitEnum.ohm;
  }
  public static CoreUnitEnum parseValue(String value) {
    if (value == null) {
      return CoreUnitEnum.getDefault();
    }
    if (value.equals(CoreUnitEnum.ohm.getValueAsString())) {
      return CoreUnitEnum.ohm;
    }
    if (value.equals(CoreUnitEnum.volt.getValueAsString())) {
      return CoreUnitEnum.volt;
    }
    return CoreUnitEnum.getDefault();
  }
}
