package deklund.util.units.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AggregateUnit = 0;
  public static final int BaseUnit = 1;
  public static final int UnitValue = 2;
  public static final int UnitsSandbox = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe1771c58997e48d1L, 0xb36b872f2d4f3bd5L);
    builder.put(0xe8f345509c8a351L, AggregateUnit);
    builder.put(0xe8f345509cc0ea2L, BaseUnit);
    builder.put(0xe8f345509c8ac09L, UnitValue);
    builder.put(0xe8f345509c90f33L, UnitsSandbox);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
