package deklund.ohml.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCircuit = createDescriptorForCircuit();
  /*package*/ final ConceptDescriptor myConceptComponent = createDescriptorForComponent();
  /*package*/ final ConceptDescriptor myConceptComponentGraph = createDescriptorForComponentGraph();
  /*package*/ final ConceptDescriptor myConceptIdealBattery = createDescriptorForIdealBattery();
  /*package*/ final ConceptDescriptor myConceptResistor = createDescriptorForResistor();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCircuit, myConceptComponent, myConceptComponentGraph, myConceptIdealBattery, myConceptResistor);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Circuit:
        return myConceptCircuit;
      case LanguageConceptSwitch.Component:
        return myConceptComponent;
      case LanguageConceptSwitch.ComponentGraph:
        return myConceptComponentGraph;
      case LanguageConceptSwitch.IdealBattery:
        return myConceptIdealBattery;
      case LanguageConceptSwitch.Resistor:
        return myConceptResistor;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCircuit() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("deklund.ohml", "Circuit", 0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c3fc5aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:66cd426c-b834-475f-8a3d-d7e3518c2104(deklund.ohml.structure)/1049114778041318490");
    b.version(2);
    b.aggregate("component", 0xe8f345509c41b68L).target(0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c486a9L).optional(true).ordered(true).multiple(true).origin("1049114778041326440").done();
    b.alias("circuit");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComponent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("deklund.ohml", "Component", 0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c486a9L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:66cd426c-b834-475f-8a3d-d7e3518c2104(deklund.ohml.structure)/1049114778041353897");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComponentGraph() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("deklund.ohml", "ComponentGraph", 0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c41b6dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:66cd426c-b834-475f-8a3d-d7e3518c2104(deklund.ohml.structure)/1049114778041326445");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIdealBattery() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("deklund.ohml", "IdealBattery", 0x27a2b5222610408aL, 0xab92b094842ed001L, 0x89cc000c48f972dL);
    b.class_(false, false, false);
    b.super_("deklund.ohml.structure.Component", 0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c486a9L);
    b.origin("r:66cd426c-b834-475f-8a3d-d7e3518c2104(deklund.ohml.structure)/620581958200563501");
    b.version(2);
    b.aggregate("voltage", 0x89cc000c48f9749L).target(0xe1771c58997e48d1L, 0xb36b872f2d4f3bd5L, 0xe8f345509c8ac09L).optional(false).ordered(true).multiple(false).origin("620581958200563529").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForResistor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("deklund.ohml", "Resistor", 0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c4c827L);
    b.class_(false, false, false);
    b.super_("deklund.ohml.structure.Component", 0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c486a9L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:66cd426c-b834-475f-8a3d-d7e3518c2104(deklund.ohml.structure)/1049114778041370663");
    b.version(2);
    b.aggregate("resistance", 0xe8f345509cc2fb2L).target(0xe1771c58997e48d1L, 0xb36b872f2d4f3bd5L, 0xe8f345509c8ac09L).optional(false).ordered(true).multiple(false).origin("1049114778041855922").done();
    b.alias("resistor");
    return b.create();
  }
}
