package deklund.ohml.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Resistance_Constraints extends BaseConstraintsDescriptor {
  public Resistance_Constraints() {
    super(MetaAdapterFactory.getConcept(0x27a2b5222610408aL, 0xab92b094842ed001L, 0xe8f345509c58abcL, "deklund.ohml.structure.Resistance"));
  }

}
